# Dockerfile
FROM python:3.11

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY singlestore_pulse-0.3-py3-none-any.whl .
RUN pip install --no-cache-dir singlestore_pulse-0.3-py3-none-any.whl
# RUN pip3 install git+https://github.com/singlestore-labs/singlestore-pulse.git@master

COPY myapp_2.py .
COPY .env .

EXPOSE 8000

CMD ["python", "myapp_2.py"]
