version: '3.8'

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8007:8000"
    depends_on:
      - otel-collector
    networks:
      - otel-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
      - ./tmp:/tmp  # Mount tmp directory for log files
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8888:8888"
    networks:
      - otel-network
    user: "0:0"  # Run as root to ensure write permissions

  tempo:
    image: grafana/tempo:latest
    command: ["-config.file=/etc/tempo.yaml"]
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
    networks:
      - otel-network
    user: "0:0"

  prometheus:
    image: prom/prometheus:latest
    command: ["--config.file=/etc/prometheus.yaml"]
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
      - prometheus-data:/prometheus
    ports:
      - "9093:9093"
    networks:
      - otel-network

  grafana:
    image: grafana/grafana:latest
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3003:3003"
    networks:
      - otel-network

networks:
  otel-network:
    driver: bridge

volumes:
  otel-collector-logs:
  tempo-data: {}
  prometheus-data: {}
  grafana-data: {}
